# GPU (Intel Iris Xe), FUSE, shared memory, SELinux disable, debug caps
container_additional_flags="--device /dev/dri --device /dev/fuse --security-opt label=disable --ipc=host --cap-add=SYS_PTRACE --cap-add=NET_RAW --volume /run/udev:/run/udev:ro"

# Export app .desktop entries to host by default
container_generate_entry=1
